name: "AWS VPC destroy"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: "Destroying lab infrastructure."
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-west-2"

    steps:
      - name: "1. Checkout code"
        uses: actions/checkout@v4

      - name: "2. Setup terraform"
        uses: hashicorp/setup-terraform@v3

      - name: "3. Terraform Init"
        run: terraform init

      - name: "4. Terraform validate"
        run: terraform validate

      - name: "5. Terraform plan (destroy)"
        run: terraform plan -destroy

      - name: "6. Terraform destroy"
        run: terraform destroy -auto-approve
